---
title: "SportsAnalytics_u3246850"
output:
  html_document: default
  pdf_document: default
date: "2023-05-07"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Load required packages
# install.packages("cli")
# library(tidyverse)
library(dplyr)
library(ggplot2)
library(reshape2)

```


```{r}

#*************2. Reading and cleaning the raw data**************************************
#*
#Load player statistics data
player_stats <- read.csv("2018-19_nba_player-statistics.csv", check.names = FALSE)

#Load player salaries data
player_salaries <- read.csv("2018-19_nba_player-salaries.csv", check.names = FALSE)

#Load team payroll data
team_payroll <- read.csv("2019-20_nba_team-payroll.csv", check.names = FALSE)

#Load team statistics data
team_stats1 <- read.csv("2018-19_nba_team-statistics_1.csv", check.names = FALSE, header = TRUE)
team_stats2 <- read.csv("2018-19_nba_team-statistics_2.csv", check.names = FALSE, header = TRUE)


# Check missing value

colSums(is.na(player_stats)) # Found missing values
colSums(is.na(player_salaries))
colSums(is.na(team_payroll))
colSums(is.na(team_stats1))
colSums(is.na(team_stats2))

# Check structure
str(player_stats)
str(player_salaries)
str(team_payroll)
str(team_stats1)
str(team_stats2)

# Changing the variable type for the analysis
team_payroll$salary <- as.numeric(gsub("[\\$,]", "", team_payroll$salary))

# Cleaning player stats team name mapping to abbreviation
player_stats <- player_stats%>% 
  mutate(Tm = case_when(
    Tm == "ATL" ~ "Atlanta Hawks",
    Tm == "BOS" ~ "Boston Celtics",
    Tm == "BRK" ~ "Brooklyn Nets",
    Tm == "CHI" ~ "Chicago Bulls",
    Tm == "CHO" ~ "Charlotte Hornets",
    Tm == "CLE" ~ "Cleveland Cavaliers",
    Tm == "DAL" ~ "Dallas Mavericks",
    Tm == "DEN" ~ "Denver Nuggets",
    Tm == "DET" ~ "Detroit Pistons",
    Tm == "GSW" ~ "Golden State Warriors",
    Tm == "HOU" ~ "Houston Rockets",
    Tm == "IND" ~ "Indiana Pacers",
    Tm == "LAC" ~ "Los Angeles Clippers",
    Tm == "LAL" ~ "Los Angeles Lakers",
    Tm == "MEM" ~ "Memphis Grizzlies",
    Tm == "MIA" ~ "Miami Heat",
    Tm == "MIL" ~ "Milwaukee Bucks",
    Tm == "MIN" ~ "Minnesota Timberwolves",
    Tm == "NOP" ~ "New Orleans Pelicans",
    Tm == "NYK" ~ "New York Knicks",
    Tm == "OKC" ~ "Oklahoma City Thunder",
    Tm == "ORL" ~ "Orlando Magic",
    Tm == "PHI" ~ "Philadelphia 76ers",
    Tm == "PHO" ~ "Phoenix Suns",
    Tm == "POR" ~ "Portland Trail Blazers",
    Tm == "SAC" ~ "Sacramento Kings",
    Tm == "SAS" ~ "San Antonio Spurs",
    Tm == "TOR" ~ "Toronto Raptors",
    Tm == "TOT" ~ "Total",
    Tm == "UTA" ~ "Utah Jazz",
    Tm == "WAS" ~ "Washington Wizards",
    TRUE ~ NA_character_
  ))

# Cleaning team payroll data to align with the brief team name
team_payroll$team<-trimws(team_payroll$team)
team_payroll <- team_payroll %>% 
  mutate(Team = case_when(
    team == "Atlanta" ~ "Atlanta Hawks",
    team == "Boston" ~ "Boston Celtics",
    team == "Brooklyn" ~ "Brooklyn Nets",
    team == "Chicago" ~ "Chicago Bulls",
    team == "Charlotte" ~ "Charlotte Hornets",
    team == "Cleveland" ~ "Cleveland Cavaliers",
    team == "Dallas" ~ "Dallas Mavericks",
    team == "Denver" ~ "Denver Nuggets",
    team == "Detroit" ~ "Detroit Pistons",
    team == "Golden State" ~ "Golden State Warriors",
    team == "Houston" ~ "Houston Rockets",
    team == "Indiana" ~ "Indiana Pacers",
    team == "LA Clippers" ~ "Los Angeles Clippers",
    team == "LA Lakers" ~ "Los Angeles Lakers",
    team == "Memphis" ~ "Memphis Grizzlies",
    team == "Miami" ~ "Miami Heat",
    team == "Milwaukee" ~ "Milwaukee Bucks",
    team == "Minnesota" ~ "Minnesota Timberwolves",
    team == "New Orleans" ~ "New Orleans Pelicans",
    team == "New York" ~ "New York Knicks",
    team == "Oklahoma City" ~ "Oklahoma City Thunder",
    team == "Orlando" ~ "Orlando Magic",
    team == "Philadelphia" ~ "Philadelphia 76ers",
    team == "Phoenix" ~ "Phoenix Suns",
    team == "Portland" ~ "Portland Trail Blazers",
    team == "Sacramento" ~ "Sacramento Kings",
    team == "San Antonio" ~ "San Antonio Spurs",
    team == "Toronto" ~ "Toronto Raptors",
    team == "Utah" ~ "Utah Jazz",
    team == "Washington" ~ "Washington Wizards",
    TRUE ~ NA_character_
  ))

```


```{r}
# ************************ 3. Exploratory analysis ********************************

#****************** 3a checking for errors and missing values within the datasets******************

# Check structure
glimpse(player_stats)
glimpse(player_salaries)
glimpse(team_payroll)
glimpse(team_stats1)
glimpse(team_stats2)

```


```{r}
#**********3b Checking distribution of variable*****************************888
#using  summary statistics and visualizations by histogram for different data frames: player_stats, player_salaries, team_payroll, team_stats1, and team_stats2.

# Summary of player
summary(player_stats)
# Distributon of player age
ggplot(player_stats, aes(x = Age)) +
  geom_histogram(binwidth = 1, color = "white", fill = "blue", alpha = 0.5) +
  labs(title = "Age Distribution", x = "Age", y = "Frequency")

# Distribution of player points
ggplot(player_stats, aes(x = PTS)) +
  geom_histogram(binwidth = 100, color = "white", fill = "blue", alpha = 0.5) +
  labs(title = "Points Distribution", x = "Points", y = "Frequency")

# Summary of player salary
summary(player_salaries)
# Distribution of player Salary
ggplot(player_salaries, aes(x = salary)) +
  geom_histogram(binwidth = 10000000, color = "white", fill = "blue", alpha = 0.5) +
  scale_y_log10() +
  labs(title = "Distribution of Player Salaries",
       x = "Salary",
       y = "Count")

# Summary of team salary
summary(team_payroll)
# Distribution of team Salary
ggplot(team_payroll, aes(x = salary)) +
  geom_histogram(binwidth = 10000000, color = "white", fill = "blue", alpha = 0.5) +
  scale_y_log10() +
  labs(title = "Distribution of Team Salaries",
       x = "Salary",
       y = "Count")

summary(team_stats1)
# Distribution of team age
ggplot(team_stats1, aes(x = Age)) +
  geom_histogram(binwidth = 1, color = "white", fill = "blue", alpha = 0.5) +
  labs(title = "Age Distribution", x = "Age", y = "Frequency")


summary(team_stats2)

ggplot(team_stats2, aes(x = PTS)) +
  geom_histogram(binwidth = 100, color = "white", fill = "blue", alpha = 0.5) +
  labs(title = "Team points Distribution", x = "Point", y = "Frequency")

```

```{r}
#********** 3c checking for relationships between variables, or differences between groups*************

# Merge player_stats and player_salaries datasets
player_stats_salaries <- left_join( player_stats,player_salaries, by = "player_name")
colSums(is.na(player_stats_salaries))
# Removing null values rows in salaries
player_stats_salaries <- player_stats_salaries[complete.cases(player_stats_salaries$player_id), ]

# Scatter plot to understand the relationship between salary and PTS of a player
ggplot(player_stats_salaries, aes(x = salary, y = PTS)) +
  geom_point() +
  labs(title = "Relationship between salary vs Points accross players",x = "Salary", y = "Points")

# There seems to be an increased positive correlation between salary of a player and points
```


```{r}
# Correlation accross different player statistics

# find numeric variables
player_stats_salaries_omit<-na.omit(player_stats_salaries)
num_vars <- sapply(player_stats_salaries_omit, is.numeric)

# subset dataframe to include only numeric variables
players_corr <- player_stats_salaries_omit[,num_vars]

# calculate correlation matrix
#cor(players_corr) calculates the correlation matrix for the players_corr dataset, which contains the relevant numeric variables from the players dataset.
cor_matrix <- cor(players_corr)
cor_matrix
#melt() function from the reshape2 package is used to convert the matrix into a long-format data frame that can be used to create a heatmap with ggplot2

cor_df <- melt(cor_matrix)
colnames(cor_df) <- c("Var1", "Var2", "Corr")

# create heatmap by ggplot()and theme_minimal() function is used to apply a minimal theme to the plot
ggplot(data = cor_df, aes(x = Var1, y = Var2, fill = Corr)) +
  geom_tile() +
  scale_fill_gradient2(low = "blue", high = "red", mid = "green", midpoint = 0) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(title = "Correlation Matrix Heatmap for players")
```



```{r}

# Merging player and team statisitcs

# Merge player_stats and team_stats_2 datasets
team_stats <- full_join(team_stats1, team_stats2, by = "Team")

team_payroll <- subset(team_payroll, select = -team)
# team_payroll <- rename(team_payroll, Team = team_full_name)

team_stats_salary<-full_join( team_stats ,team_payroll, by = "Team")
player_stats_salaries <- rename(player_stats_salaries, Team = Tm)

# Merging the player and team stats as a master dataset

# master_player_team<- full_join(player_stats_salaries,team_stats_salary, by = "Team")
# 
# colSums(is.na(master_player_team))
# 
# master_player_team_omit<-na.omit(master_player_team)
# 
# colSums(is.na(master_player_team_omit))

#developing a reproducible data model that captures relevant player statistics and incorporates #appropriate statistical methods is essential for identifying the best five starting players for each #position for the Chicago Bulls. By creating a model that is flexible and scalable, we can update and #modify it in the future to make informed decisions based on the latest data

```


```{r}
# 4.4. Data modelling and results


# Create linear regression model to predict PTS based on salary
lm_model <- lm(PTS ~ salary +  FGA + FTA, data = player_stats_salaries)

# Display model summary
summary(lm_model)

# PTS = -8.121 + 2.533e-07(salary) + 1.038(FGA) + 0.8713(FTA)




#***************** Model Interpretation *************************************
# In the linear regression model with PTS as the dependent variable and salary, FGA, and FTA as independent # variables, the coefficients for FGA and FTA are significant with p-values < 2e-16, indicating that these # variables are strongly associated with PTS. However, the coefficient for salary is not significant with a # p-value of 0.288, suggesting that salary is not a good predictor of PTS. The adjusted R-squared value of # 0.9922 indicates that the model explains a high proportion of the variance in PTS, and the F-statistic of # 2.915e+04 with a p-value < 2.2e-16 indicates that the overall model is significant. The residual standard # error of 40.32 suggests that the model has a moderate level of error in predicting PTS, and the normal Q-Q # plot and residual vs. fitted plot do not show any major departures from normality or homoscedasticity # assumptions

```

```{r}
# Assumption checking

# 1. homoscedasticity

# Plot residuals vs. fitted values
plot(lm_model$fitted.values, lm_model$residuals, type = "p", col = "blue",
     xlab = "Fitted Values", ylab = "Residuals",
     main = "Residuals vs. Fitted Values Plot")

# 2. Normality plot

#Normal probability plot
qqnorm(lm_model$residuals, main = "Normal Probability Plot")


```


```{r}
# ***** 5. Player recommendation in each position ***************************

# Top 5 player with regards to position based on Cost effectiveness

# Calculate cost-effectiveness score
player_stats_salaries$cost_effectiveness <- player_stats_salaries$PTS / player_stats_salaries$salary

# Select top player for each position
point_guard <- player_stats_salaries %>%
  filter(Pos == "PG") %>%
  slice_max(cost_effectiveness)

shooting_guard <- player_stats_salaries %>%
  filter(Pos == "SG") %>%
  slice_max(cost_effectiveness)

small_forward <- player_stats_salaries %>%
  filter(Pos == "SF") %>%
  slice_max(cost_effectiveness)

power_forward <- player_stats_salaries %>%
  filter(Pos == "PF") %>%
  slice_max(cost_effectiveness)

center <- player_stats_salaries %>%
  filter(Pos == "C") %>%
  slice_max(cost_effectiveness)

# Combine selected players into final output
top_five <- bind_rows(
  point_guard %>% select(player_name, Team, Pos, Age, G, PTS, salary, cost_effectiveness),
  shooting_guard %>% select(player_name,Team, Pos, Age, G, PTS, salary, cost_effectiveness),
  small_forward %>% select(player_name, Team, Pos, Age, G, PTS, salary, cost_effectiveness),
  power_forward %>% select(player_name, Team, Pos, Age, G, PTS, salary, cost_effectiveness),
  center %>% select(player_name, Team, Pos, Age, G, PTS, salary, cost_effectiveness)
)

top_five_budget <- sum(top_five$salary)

top_five_budget

# Output starting five
top_five


```

```{r}

# Top 5 player with regards to position based on Cost effectiveness from Chicago Bulls team

chicago_players <- player_stats_salaries %>% filter(Team == "Chicago Bulls")


# Select top player for each position
point_guard <- chicago_players %>%
  filter(Pos == "PG") %>%
  slice_max(cost_effectiveness)

shooting_guard <- chicago_players %>%
  filter(Pos == "SG") %>%
  slice_max(cost_effectiveness)

small_forward <- chicago_players %>%
  filter(Pos == "SF") %>%
  slice_max(cost_effectiveness)

power_forward <- chicago_players %>%
  filter(Pos == "PF") %>%
  slice_max(cost_effectiveness)

center <- chicago_players %>%
  filter(Pos == "C") %>%
  slice_max(cost_effectiveness)

# Combine selected players into final output
chicago_top_five <- bind_rows(
  point_guard %>% select(player_name, Team, Pos, Age, G, PTS, salary, cost_effectiveness),
  shooting_guard %>% select(player_name,Team, Pos, Age, G, PTS, salary, cost_effectiveness),
  small_forward %>% select(player_name, Team, Pos, Age, G, PTS, salary, cost_effectiveness),
  power_forward %>% select(player_name, Team, Pos, Age, G, PTS, salary, cost_effectiveness),
  center %>% select(player_name, Team, Pos, Age, G, PTS, salary, cost_effectiveness)
)

# Output starting five
chicago_top_five


chicago_top_five_budget <- sum(chicago_top_five$salary)

chicago_top_five_budget

```

```{r}

# Top 5 players based on Points alone, neglecting salary

# Select top player for each position
point_guard_top <- player_stats_salaries %>%
  filter(Pos == "PG") %>%
  slice_max(PTS)

shooting_guard_top <- player_stats_salaries %>%
  filter(Pos == "SG") %>%
  slice_max(PTS)

small_forward_top <- player_stats_salaries %>%
  filter(Pos == "SF") %>%
  slice_max(PTS)

power_forward_top <- player_stats_salaries %>%
  filter(Pos == "PF") %>%
  slice_max(PTS)

center_top <- player_stats_salaries %>%
  filter(Pos == "C") %>%
  slice_max(PTS)

# Combine selected players into final output
top_five_cost <- bind_rows(
  point_guard_top %>% select(player_name, Team, Pos, Age, G, PTS, salary),
  shooting_guard_top %>% select(player_name,Team, Pos, Age, G, PTS, salary),
  small_forward_top %>% select(player_name, Team, Pos, Age, G, PTS, salary),
  power_forward_top %>% select(player_name, Team, Pos, Age, G, PTS, salary),
  center_top %>% select(player_name, Team, Pos, Age, G, PTS, salary)
)

top_five_cost_budget <- sum(top_five_cost$salary)

top_five_cost_budget

# Output starting five not based on cost effectiveness
top_five_cost



```


```{r}
# Top 5 irrespective of position

player_stats_salaries[order(-player_stats_salaries$salary),][1:5,] %>% select(player_name, Team, Pos, Age, G, PTS, salary)
```

